### ISSUE TITLE
Driver for Linux kernel v3.10

### ISSUE THREAD

**Issue by shrikrishnakatore** [BoschSensortec/BNO055_driver#5]
Hi,
I am trying to add bno055 support to the linux kernelv3.10. Is there any patch available or available driver?

Thanks

**Comment by BoschSensortec** [comment]
Hi @shrikrishnakatore ,

There is currently no known support from us for the BNO055 on the Linux Kernel 3.10. It is possible to create a driver using the code available in this repository.

**Comment by shrikrishnakatore** [comment]
Ok .
Thanks
